<?php

namespace Database\Seeders;

use App\Models\Products;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $product = [
            "AMPHITOL 1 KG",
            "AMMONIUM BICARBONATE 1 KG",
            "BEESWAX 1 KG",
            "BEESWAX 100 GRAM",
            "BEESWAX 500 GRAM",
            "CAMPHOR/ KAMPER 1 KG",
            "CAMPHOR/ KAMPER 100 GRAM",
            "CAMPHOR/ KAMPER 500 GRAM",
            "CARBOPOL 980 1 KG",
            "CARBOPOL 980 100 GR",
            "CARBOPOL 980 500 GR",
            "CASTOR OIL 1 LITER",
            "CASTOR OIL 100 ML",
            "CASTOR OIL 20 LITER",
            "CASTOR OIL 5 LITER",
            "CASTOR OIL 500 ML",
            "CITRIC ACID 1 KG",
            "CITRIC ACID 1 ZAK 25 KG",
            "CMC NA 1 KG",
            "CMC NA 1 ZAK 25 KG",
            "CMC NA 100 GR",
            "CMC NA 500 GR",
            "CORN STARCH 1 KG",
            "CORN STARCH 1 ZAK 25 KG",
            "DPG / SOLVIOL 1 LITER",
            "DPG / SOLVIOL 20 LITER",
            "DPG / SOLVIOL 5 LITER",
            "DPG / SOLVIOL 500 ML",
            "ETHANOL / PELARUT PARFUM 1 LT",
            "ETHANOL / PELARUT PARFUM 500 ML",
            "GUAR GUM 1 KG",
            "GUAR GUM 1 ZAK 25 KG",
            "GUAR GUM 500 GR",
            "H2O2 50% 1 JER 30 KG",
            "H2O2 50% 1 KG",
            "H2O2 50% 5 KG",
            "HNO3 / Nitric 68% 1 Kg",
            "HNO3 / Nitric 68% 35 Kg",
            "HF 55% / Hydro Fluoric 500 GR",
            "HF 55% / Hydro Fluoric 1 Kg",
            "HF 55% / Hydro Fluoric 25 Kg",
            "HARDENER RESIN EPOXY 500 GR",
            "ISOPROPYL ALCOHOL 1 LITER",
            "ISOPROPYL ALCOHOL 20 LITER",
            "ISOPROPYL ALCOHOL 5 LITER",
            "ISP 1 KG",
            "KAPORIT CAIR 1 JER 35 KG",
            "KAPORIT CAIR 1 KG",
            "KAPORIT GRANULAR 1 KG",
            "KAPORIT GRANULAR 1 PAIL 50 KG",
            "KAPORIT TABLET BESAR 1 KG",
            "KAPORIT TABLET BESAR 1 PAIL 50 KG",
            "KAPORIT TABLET KECIL 1 KG",
            "KAPORIT TABLET KECIL 1 PAIL 50 KG",
            "KOH FLAKES 1 KG",
            "KOH FLAKES 25 KG",
            "MENTHOL CRYSTAL 1 KG",
            "MENTHOL CRYSTAL 100 GR",
            "MENTHOL CRYSTAL 500 GR",
            "METHANOL / PELARUT PARFUM 1 LITER",
            "METHANOL / PELARUT PARFUM 5 LITER",
            "METHYL SALYCILATE / METSAL 1 JER 25 KG",
            "METHYL SALYCILATE / METSAL 1 KG",
            "METHYL SALYCILATE / METSAL 5 KG",
            "NACL / GARAM KROSOK 1 KG",
            "NACL / GARAM KROSOK 500 GRAM",
            "NIACINAMIDE POWDER 100 GR",
            "NIACINAMIDE POWDER 250 GR",
            "NIACINAMIDE POWDER 500 GR",
            "OLEORESIN CAPSICUM 1 JT SHU WS 1 KG",
            "OLEORESIN CAPSICUM 1 JT SHU WS 100 GR",
            "OLEORESIN CAPSICUM 1 JT SHU WS 250 GR",
            "OLEORESIN CAPSICUM 1 JT SHU WS 500 GR",
            "OXALIC ACID 1 KG",
            "OXALIC ACID 1 ZAK 25 KG",
            "PAC 1 KG",
            "PAC 1 ZAK 25 KG",
            "PARAFIN WAX 1 KG",
            "PARAFIN WAX 1 ZAK 50 KG",
            "PEG 40 1 KG",
            "PEG 40 20 KG",
            "PEG 40 5 KG",
            "PEG 40 500 GR",
            "PHOSPHORIC ACID 1 JER 35 KG",
            "PHOSPHORIC ACID 1 KG",
            "PHOSPHORIC ACID 5 KG",
            "POTASSIUM SORBATE 1 BOX 25 KG",
            "POTASSIUM SORBATE 1 KG",
            "POTASSIUM SORBATE 500 GR",
            "PROPYLENE GLYCOL 1 KG",
            "PROPYLENE GLYCOL 20 KG",
            "PROPYLENE GLYCOL 500 GR",
            "PROPYLENE GLYCOL 5 KG",
            "RESIN EPOXY SET 1,5 KG",
            "RESIN EPOXY SET 750 GR",
            "RESIN LYCAL KERAS 1011 1 GALON",
            "RESIN LYCAL KERAS 1011 1 KG",
            "RESIN LYCAL KERAS 1011 500 GR",
            "RESIN LYCAL LENTUR 1 GALON",
            "RESIN LYCAL LENTUR 750 GRAM",
            "RESIN MERAH 1 KG + KATALIS 50 ML",
            "RESIN MERAH 5 KG + KATALIS 250 ML",
            "SODA API 1 KG",
            "SODA API 1 ZAK 25 KG",
            "SODA API 500 GR",
            "SODA ASH DENSE 1 KG",
            "SODA ASH DENSE 1 ZAK 50 KG",
            "SODA ASH LIGHT 1 KG",
            "SODA ASH LIGHT 1 ZAK 50 KG",
            "SODA KUE / SODIUM BICARBONATE 1 KG",
            "SODA KUE / SODIUM BICARBONATE 25 KG",
            "SODIUM BENZOATE 1 KG",
            "SODIUM BENZOATE 1 ZAK 25 KG",
            "SODIUM METABISULFIT / SMB 1 KG",
            "SODIUM METABISULFIT / SMB 1 ZAK 25 KG",
            "SODIUM PECARBONATE / H2O2 BUBUK 1 KG",
            "SODIUM PECARBONATE / H2O2 BUBUK 1 ZAK",
            "SODIUM PECARBONATE / H2O2 BUBUK 500 GRAM",
            "SODIUM SULFAT 1 KG",
            "SODIUM SULFAT 1 ZAK 50 KG",
            "SOLVENT / ACETON 1 LITER",
            "SOLVENT / ACETON 20 LITER",
            "SOLVENT / ACETON 5 LITER",
            "STEARIC ACID 1 KG",
            "STEARIC ACID 1 ZAK 25 KG",
            "STEARYL ALCOHOL 1 KG",
            "STEARYL ALCOHOL 20 KG",
            "STPP 1 KG",
            "STPP 1 ZAK 25 KG",
            "STPP 500 GR",
            "TAWAS 1 KG",
            "TEXAPON / EMAL 270 N 1 KG",
            "TRISODIUM CITRATE 1 KG",
            "TRISODIUM CITRATE 500 GR",
            "VASELINE 1 KG",
            "VG / GLISERIN 1 KG",
            "VG / GLISERIN 20 KG",
            "VG / GLISERIN 5 KG",
            "VG / GLISERIN 500 GR",
            "WHITE OIL 1 LITER",
            "WHITE OIL 20 LITER",
            "WHITE OIL 5 LITER",
            "XANTHAN GUM 1 KG",
            "XANTHAN GUM 100 GR",
            "XANTHAN GUM 500 GR",
            "AVOCADO OIL 30 ML",
            "AVOCADO OIL 50 ML",
            "AVOCADO OIL 250 ML",
            "AVOCADO OIL 500 ML",
            "ARGAN OIL 30 ML",
            "ARGAN OIL 50 ML",
            "CALENDULA OIL 30 ML",
            "CALENDULA OIL 50 ML",
            "CALENDULA OIL 250 ML",
            "CALENDULA OIL 500 ML",
            "CITRONELLA OIL 30 ML",
            "CITRONELLA OIL 50 ML",
            "GOLDEN JOJOBA OIL 30 ML",
            "GOLDEN JOJOBA OIL 50 ML",
            "GOLDEN JOJOBA OIL 250 ML",
            "GOLDEN JOJOBA OIL 500 ML",
            "GRAPESEED OIL 30 ML",
            "GRAPESEED OIL 50 ML",
            "KUKUI NUT OIL 30 ML",
            "KUKUI NUT OIL 50 ML",
            "LEMON OIL 30 ML",
            "LEMON OIL 50 ML",
            "PEPPERMINT ARVENSIS OIL 30 ML",
            "PEPPERMINT ARVENSIS OIL 50 ML",
            "PEPPERMINT ARVENSIS OIL 100 ML",
            "RICEBRAN OIL 30 ML",
            "RICEBRAN OIL 50 ML",
            "SUNFLOWER OIL 30 ML",
            "SUNFLOWER OIL 50 ML",
            "SUNFLOWER OIL 500 ML",
            "SWEET ALMOND OIL 30 ML",
            "SWEET ALMOND OIL 50 ML",
            "SWEET ALMOND OIL 500 ML",
            "SWEET ORANGE OIL 30 ML",
            "SWEET ORANGE OIL 50 ML",
            "TEA TREE OIL 30 ML",
            "TEA TREE OIL 50 ML",
            "WHEATGERM OIL 30 ML",
            "WHEATGERM OIL 50 ML",
            "BIBIT PARFUM DARK ROSE 500 ML",
            "BIBIT PARFUM OCEAN FRESH 500 ML",
            "BIBIT PARFUM SAKURA 100 ML",
            "BIBIT PARFUM SAKURA 250 ML",
            "BIBIT PARFUM SAKURA 500 ML",
            "BIBIT PARFUM SNAPPY 100 ML",
            "BIBIT PARFUM SNAPPY 250 ML",
            "BIBIT PARFUM SNAPPY 500 ML",
            "BIBIT PARFUM OCEAN FRESH 100 ML",
            "BIBIT PARFUM OCEAN FRESH 250 ML",
            "BIBIT PARFUM OCEAN FRESH 500 ML",
            "BIBIT PARFUM MELON CANTALOUPE 100 ML",
            "BIBIT PARFUM MELON CANTALOUPE 250 ML",
            "BIBIT PARFUM MELON CANTALOUPE 500 ML",
            "BIBIT PARFUM SWEET POPPY 100 ML",
            "BIBIT PARFUM SWEET POPPY 250 ML",
            "BIBIT PARFUM SWEET POPPY 500 ML",
            "BIBIT PARFUM LAVENDER 100 ML",
            "BIBIT PARFUM LAVENDER 250 ML",
            "BIBIT PARFUM LAVENDER 500 ML",
            "BIBIT PARFUM LEMON SUNLIGHT 100 ML",
            "BIBIT PARFUM LEMON SUNLIGHT 250 ML",
            "BIBIT PARFUM LEMON SUNLIGHT 500 ML",
            "BIBIT PARFUM AKASIA 100 ML",
            "BIBIT PARFUM AKASIA 250 ML",
            "BIBIT PARFUM AKASIA 500 ML",
            "MENTHOL CRYSTAL 50 GR (SAMPLE)",
            "SODIUM POLYACRYLATE 1 KG",
            "CETHYL ALCOHOL 1 KG",
            "CAPSICUM EX AKAY 1 KG"
        ];
        $faker = \Faker\Factory::create();
        foreach ($product as $item) {
            $data = new Products();
            $data->name = $item;
            $data->price = $faker->randomFloat(2, 10000, 100000);
            $data->quantity = $faker->numberBetween(1, 1000);
            $data->save();
        }
    }
}
